Add data persistence and refactor tests
piecubed/fenix pull request #19
Opened 2022-08-09 03:36 UTC by piecubed

2022-08-09 04:08 UTC, piecubed commented
Weird debugging thing was because of an issue only on GitHub actions, not on my computer.

2022-08-10 14:17 UTC, JosiahWI commented
There still seems to be a timing issue on the windows-latest CI. We just removed Windows and MacOSX from the CI to reduce CI minutes, but maybe we should consider adding a Windows build back in on both the server and client.

2022-08-11 17:49 UTC, JosiahWI commented on src/server/handlers.go
>  		Message: msg.Message,
Message content needs to be tested.

2022-08-11 17:49 UTC, JosiahWI commented on src/server/handlers.go
> +		client.OutgoingPayloadQueue <- websocket_models.GenericError{Error: "DatabaseError"}
Test this.

2022-08-11 17:49 UTC, JosiahWI commented on src/server/handlers.go
> +	msg_broadcast.MessageID = db_msg.MessageID.Hex()
Test this.

2022-08-11 17:49 UTC, JosiahWI commented on src/server/handlers.go
> +	if hist.From == 0 || hist.To == 0 {
Test this.

2022-08-11 17:50 UTC, JosiahWI commented on src/server/server_hub.go
> +			w.WriteHeader(http.StatusNotFound)
Test this.

2022-08-11 17:52 UTC, JosiahWI requested changes
Besides all the mentioned tests, please remember to run `go fmt`.

2022-08-11 19:38 UTC, piecubed commented
I did run gofmt.

2022-08-12 20:45 UTC, piecubed commented on src/server/handlers.go
>  		Message: msg.Message,
It is.

2022-08-14 19:52 UTC, JosiahWI requested changes
Please add a test that the message IDs are valid.

2022-08-14 21:26 UTC, JosiahWI approved these changes

2022-08-14 21:27 UTC, merged